# Generated by Django 4.1 on 2024-09-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=72)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(blank=True, max_length=14, null=True)),
                ('instagram', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram', models.CharField(blank=True, max_length=32, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dta_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dta_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=96)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estoque', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('dta_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dta_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('canal_venda', models.CharField(max_length=28)),
                ('tipo_frete', models.CharField(max_length=32)),
                ('rastreio_frete', models.CharField(blank=True, max_length=254, null=True)),
                ('status_frete', models.CharField(max_length=32)),
                ('ativo', models.BooleanField(default=True)),
                ('dta_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dta_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avec_amour_vendas.cliente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avec_amour_vendas.item')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=18)),
                ('sinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('dta_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dta_atualizacao', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avec_amour_vendas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=96)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('ativo', models.BooleanField(default=True)),
                ('dta_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dta_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='avec_amour_vendas.cliente')),
            ],
        ),
    ]
