# Generated by Django 4.1 on 2024-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec_amour_vendas', '0002_remove_pedido_item_pedido_itens_alter_item_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=96),
        ),
    ]
